apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-cluster
spec:
  selector:
    matchLabels:
      app: eventstore-cluster 
  serviceName: eventstore-cluster
  template:
    metadata:
      labels:
        app: eventstore-cluster
    spec:
      containers:
      - name: eventstore
        volumeMounts:
        - name: eventstore-cluster-data
          mountPath: /var/lib/eventstore
  volumeClaimTemplates:
  - metadata:
      name: eventstore-cluster-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-premium-retain"
      resources:
        requests:
          storage: 5Gi
