export enum Theme {
    Energy = 'Energy',
    Agriculture = 'Agriculture',
    Transport = 'Transport',
    Waste = 'Waste',
    SoilAndUnderground = 'SoilAndUnderground',
    Sound = 'Sound',
    EnvironmentalChange = 'EnvironmentalChange',
    Air = 'Air',
    NatureAndLandscape = 'NatureAndLandscape',
    Water = 'Water',
    Safety = 'Safety',
    SpatialPlanning = 'SpatialPlanning',
    Watermanagement = 'Watermanagement',
    Aviation = 'Aviation',
    PublicTransport = 'PublicTransport',
    RailAndRoadTraffic = 'RailAndRoadTraffic',
    Shipping = 'Shipping',
    Construction = 'Construction',
    Housing = 'Housing',
    Health = 'Health',
}
