apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-cluster
spec:
  replicas: 1 # Needs to be the same as EVENTSTORE_CLUSTER_SIZE
  template:
    spec:
      containers:
      - name: eventstore
        env:
        - name: EVENTSTORE_CLUSTER_SIZE #Needs to match spec.replicas
          value: "1"
        volumeMounts:
        - name: local-vol
          mountPath: /var/lib/eventstore
  volumeClaimTemplates:
  - metadata:
      name: local-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
