# Use the production image as base image
FROM sensrnet-registry-backend_registry-backend

# Copy the test files
COPY test test

# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev

# 1. Get test packages; AND
# 2. Install our test framework - jest
RUN npm update && \
    npm install -g jest

# Override the command, to run the test instead of the application
CMD ["jest", "--config", "./test/jest-e2e.json", "--forceExit"]
