version: '3.7'

services:
  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
      - EVENTSTORE_INT_IP=0.0.0.0
      - EVENTSTORE_EXT_IP=0.0.0.0
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - backend

  mongo:
    image: mongo
    ports:
      - 27017:27017

  registry-backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - eventstore
      - mongo
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_PORT=1113
      - EVENT_STORE_HOST=eventstore
      - JWT_ACCESS_EXPIRES_IN=86400
      - JWT_SECRET=example-secret-key
      - JWT_REFRESH_EXPIRES_IN=604800
    links:
      - eventstore
