# Use the production image as base image
FROM sensrnet-registry-backend_registry-backend

# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev

# 1. Get test packages; AND
# 2. Install our test framework - jest
COPY ./package*.json ./
RUN npm update && \
    npm ci
    
# Copy the test files
COPY tsconfig*.json ./
COPY src src
COPY test test

# Override the command, to run the test instead of the application
CMD ["npm", "run", "test:e2e"]
