version: '3.7'

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_DEV=true
      - EVENTSTORE_MEM_DB=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    command:
      --dev --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls

  mongo:
    image: mongo
    ports:
      - 27017:27017

  registry-backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - eventstore
      - mongo
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_PORT=1113
      - EVENT_STORE_HOST=eventstore
      - JWT_ACCESS_EXPIRES_IN=86400
      - JWT_SECRET=example-secret-key
      - JWT_REFRESH_EXPIRES_IN=604800
    links:
      - eventstore
