apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: demo

commonLabels:
  environment: demo

patchesStrategicMerge:
- eventstore/patch.yaml
- mongo/patch.yaml
- mongo/pvc.yaml
