apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  template:
    spec:
      containers:
      - name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: local-mongo
