apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mongo
  namespace: sensrnet-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
