apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-backend
spec:
  template:
    spec:
      containers:
      - name: registry-backend
        env:
        - name: NODE_ID
          value: node_test-aks
