apiVersion: v1
kind: Service
metadata:
  name: eventstore-cluster
spec:
  clusterIP: "None"
  ports:
  - name: eventstore-web
    port: 2113
  - name: eventstore-tcp
    port: 1113
  - name: gossip
    port: 2112
