apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-cluster
spec:
  serviceName: eventstore-cluster
  replicas: 3 # Needs to be the same as EVENTSTORE_CLUSTER_SIZE
  template:
    spec:
      containers:
      - name: eventstore
        image: eventstore/eventstore:release-5.0.8
        env:
        - name: EVENTSTORE_CLUSTER_SIZE #Needs to match spec.replicas
          value: "3"
        - name: EVENTSTORE_DISCOVER_VIA_DNS
          value: "true"
        - name: EVENTSTORE_CLUSTER_DNS #Should match service name
          value: "eventstore-cluster"
        - name: EVENTSTORE_DEV
          value: "true"
        - name : EVENTSTORE_MEM_DB
          value: "false"
        - name: EVENTSTORE_RUN_PROJECTIONS
          value: "All"
        - name: EVENTSTORE_START_STANDARD_PROJECTIONS
          value: "true"
        - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
          value: "true"
        - name: EVENTSTORE_DISABLE_EXTERNAL_TCP_TLS
          value: "true"
        - name: EVENTSTORE_EXT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports: 
        - name: eventstore-web
          containerPort: 2113
        - name: eventstore-tcp
          containerPort: 1113
        - name: gossip
          containerPort: 2112
        volumeMounts:
        - name: eventstore-cluster-data
          mountPath: /var/lib/eventstore
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: eventstore-web
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: eventstore-web
          initialDelaySeconds: 5
          periodSeconds: 5
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - eventstore
            topologyKey: "kubernetes.io/hostname"
