apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: registry-backend
  name: registry-backend
  namespace: sensrnet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registry-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: registry-backend
    spec:
      containers:
      - env:
        - name: EVENT_STORE_HOST
          value: eventstore-cluster
        - name: EVENT_STORE_PORT
          value: "1113"
        - name: JWT_SECRET
          value: example-secret-key
        - name: MONGO_DATABASE
          value: sensrnet
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        - name: NODE_ID
          value: node_1
        - name: PORT
          value: "3000"
        image: sensrnetregistry.azurecr.io/sensrnet/registry-backend:latest
        name: registry-backend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: registry-backend
  name: registry-backend
  namespace: sensrnet-backend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    io.kompose.service: registry-backend
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-backend-ingress
  namespace: sensrnet-backend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.backend.loadbalancer.stickiness: "true"
spec:
  rules:
  - host: sensrnet-test.westeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: registry-backend
          servicePort: 80
        path: /api/
