apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry-backend

resources:
  - namespace.yaml

commonLabels:
  app.kubernetes.io/name: sensrnet

bases:
  - registry-backend
  - eventstore
  - mongo
