apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-backend
spec:
  template:
    spec:
      containers:
      - image: sensrnetregistry.azurecr.io/sensrnet/registry-backend:latest
        name: registry-backend
