apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: registry-backend-ingress
spec:
  entryPoints:
  - http
  routes:
  - kind: Rule
    match: PathPrefix(`/api/`)
    services:
    - kind: Service
      name: registry-backend
      port: 80
      sticky:
        cookie:
          httpOnly: true
