apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: viewer

commonLabels:
  environment: viewer

patchesStrategicMerge:
- eventstore/patch.yaml
- mongo/patch.yaml
- mongo/pvc.yaml
- registry-backend/deployment.yaml
