export enum Description {
    CameraFixed = 'Camera Fixed',
    CameraMobile = 'Camera Mobile',
    Flowmeter = 'Flowmeter',
    HeightDetectionDevice = 'Height Detection Device',
    DetectionLoop = 'Detection Loop',
    WeatherStation = 'Weather Station',
    SpeedDetectionDevice = 'Speed Detection Device',
    WaterLevelMeter = 'Water Level Meter',
    WindGauge = 'Wind Gauge',
    LightCell = 'Light Cell',
    GMSSensor = 'GMS Sensor',
    RadarDetector = 'Radar Detector',
    FineDustSensor = 'Fine Dust Sensor',
    UVSensor = 'UV Sensor',
    MotionSensor = 'Motion Sensor',
    FireDetector = 'Fire Detector',
    MicrophoneOrSoundMeter = 'Microphone or SoundMeter',
    Beacon = 'Beacon',
}
