export enum SensorType {
    NavigationBeacon = 'NavigationBeacon',
    EnvironmentalZoneCameras = 'EnvironmentalZoneCameras',
    SecurityCamera = 'SecurityCamera',
    TrafficFlashlight = 'TrafficFlashlight',
    WeatherStation = 'WeatherStation',
    WindGauge = 'WindGauge',
    WasteContainers = 'WasteContainers',
    FineDustSensor = 'FineDustSensor',
    UVSensor = 'UVSensor',
    LightCell = 'LightCell',
    MotionSensor = 'MotionSensor',
    FireDetector = 'FireDetector',
    WaterLevelMeter = 'WaterLevelMeter',
    MicrophoneOrSoundMeter = 'MicrophoneOrSoundMeter',
    PedometerCounters = 'PedometerCounters',
    RadarDetector = 'RadarDetector',
    GMSSensor = 'GMSSensor',
    DetectionLoop = 'DetectionLoop',
    HeightDetectionDevice = 'HeightDetectionDevice',
}
