export enum Theme {
    Energy = 'Energy',
    AgricultureFishingFoodQuality = 'Agriculture, Fishing or Food Quality',
    Transport = 'Transport',
    Waste = 'Waste',
    Soil = 'Soil',
    Sound = 'Sound',
    ClimateChange = 'Climate Change',
    Air = 'Air',
    NatureLandscapeManagement = 'Nature and Landscape Management',
    Water = 'Water',
    Safety = 'Safety',
    SpatialPlanning = 'Spatial Planning',
    WaterManagement = 'Water management',
    Aviation = 'Aviation',
    PublicTransport = 'Public Transport',
    RailRoadTraffic = 'Rail or Road Traffic',
    Shipping = 'Shipping',
    BuildRemodel = 'Building or Remodelling',
    HousingMarket = 'Housing Market',
    HealthRisks = 'Health Risks',
}
