# This GitHub Action performs the following steps:
# - Deploying image on K8s cluster
#
# Prerequisites
# - AKS cluster w/ attached ACR
# - Github secret: KUBE_CONFIG containing context info for cluster access
name: Deploy to AKS
on:
  release:
    types: [published]

env:
  REGISTRY: sensrnetregistry.azurecr.io
  USERNAME: sensrnet
  IMAGE: registry-backend

# There is basically one deploy job, but triplicated. Once for each AKS cluster :)
jobs:
  deploy-to-aks-gemeente-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/kubernetes-set-context
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          # context: sensrnet-gemeente-a

      # k8s-set-context has context param. However, it doesn't seem to work (as of 2020-07-29)
      # https://github.com/Azure/k8s-set-context/issues/10
      # Set context manually for now
      - run: kubectl config use-context sensrnet-gemeente-a

      # Create manifest file using Kustomize
      # https://github.com/Azure/k8s-bake
      - uses: azure/k8s-bake@v1
        with:
          renderEngine: 'kustomize'
          kustomizationPath: './deployment/overlays/labs-gemeente-a/'
          kubectl-version: 'latest'
        id: bake

      # Use manifest file from previous step to deploy on cluster
      # https://github.com/marketplace/actions/deploy-to-kubernetes-cluster
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: sensrnet-backend
          # Overwrite image tag with release version in manifest (as it contains :latest by default)
          images: |
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE }}:${{ github.event.release.tag_name }}
